juego:
	javac Juego.java

pikinims:
	javac Pikinim.java Amarillo.java Cyan.java Magenta.java

zonas:
	javac Zona.java Ilevantable.java Pieza.java Pildora.java Muralla.java Enemigo.java

run: pikinims zonas juego
	java Juego

clean:
	rm -rf *.class